# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:"dhcp-server" => {
        :box_name => "centos/7",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.77.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net"},
                ]
  },
  :"web-client" => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.77.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net"},
                ]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "dhcp-server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sudo yum install epel-release -y
            sudo yum install nano net-tools xinetd tftp-server dhcp -y
            sudo systemctl start dhcpd
            systemctl enable dhcpd
          SHELL
        when "web-client"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sudo yum install epel-release -y
            sudo yum install nano httpd net-tools, wget -y
            sudo systemctl start httpd
            sudo systemctl enable httpd
             SHELL
        end

    end

  end
  
  
end
