# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", id: "vagrant", automount: true
  config.vm.define "web" do |server|
    server.vm.box = "centos/7"
    server.vm.hostname = "web"
    server.vm.network :private_network, ip: "192.168.11.170"
    #server.vm.provider "virtualbox" do |vb|
     #  vb.memory = "1024"
     #  second_disk = './second_hdd.vdi'
     #  vb.customize ['createhd', '--filename', second_disk, '--format', 'VDI', '--size', 2 * 1024]
     #  vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 0, '--device', 1, '--type', 'hdd', '--medium', second_disk]
     #end
     server.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
              yum install -y epel-release
              yum install -y nginx setools-console policycoreutils-python nano
         SHELL

  end

  config.vm.define "log" do |log|
    log.vm.box = "centos/7"
    log.vm.hostname = "log"
    log.vm.network :private_network, ip: "192.168.11.171"
    
  end
      config.vm.provision "shell", path: "script.sh"
end
