# Describe VMs
MACHINES = {
  # VM name "kernel update"
  :"nfs1-server" => {
              # VM box
              :box_name => "centos/7",
              # VM CPU count
              :cpus => 2,
              # VM RAM size (Mb)
              :memory => 2048,
              # networks
              :net => [],
              # forwarded ports
              :forwarded_port => [],
              :ip_addr => '192.168.11.121'
            },
:"nfs1-client" => {
              # VM box
              :box_name => "centos/7",
              # VM CPU count
              :cpus => 2,
              # VM RAM size (Mb)
              :memory => 2048,
              # networks
              :net => [],
              # forwarded ports
              :forwarded_port => [],
              :ip_addr => '192.168.11.122'
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    # Disable shared folders
    config.vm.synced_folder ".", "/vagrant", disabled: true
    # Apply VM config
    config.vm.define boxname do |box|
      # Set VM base box and hostname
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      # Additional network config if present
      #if boxconfig.key?(:net)
      #  boxconfig[:net].each do |ipconf|
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      #  end
      #end
      # Port-forward config if present
      #if boxconfig.key?(:forwarded_port)
      #  boxconfig[:forwarded_port].each do |port|
      #    box.vm.network "forwarded_port", port
      #  end
      #end
      # VM resources config
      box.vm.provider "virtualbox" do |v|
        # Set VM RAM size and CPU count
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
    end
    config.vm.provision :shell, path: "nfs.sh", run: 'always'
  end
end
